src/Web/DrugTrade.Web/Controllers/PharmacyController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DrugTrade.Services.Data;
using Microsoft.AspNetCore.Authorization;
using DrugTrade.Web.ViewModels.Pharmacies;
using System.IO;
using DrugTrade.Data.Models;

namespace DrugTrade.Web.Controllers
{
    public class PharmacyController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IPharmaciesService pharmaciesService;

        public PharmacyController(IUsersService usersService, IPharmaciesService pharmaciesService)
        {
            this.usersService = usersService;
            this.pharmaciesService = pharmaciesService;
        }

        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(PharmacyInputModel inputModel)
        {
            ApplicationUser user = this.usersService.GerUserByName(this.User.Identity.Name); 

            await this.pharmaciesService.AddAsync(inputModel.Name, inputModel.Address, inputModel.ContactNumber, inputModel.ProfileImage, user.Id, user);

            return this.Redirect("/");
        }

        [Authorize]
        public async Task<IActionResult> List()
        {
            var pharmacies = this.pharmaciesService.GetAllPharmacies();

            var userId = this.usersService.GerUserByName(this.User.Identity.Name).Id;

            PharmaciesViewModel viewModel = new PharmaciesViewModel(pharmacies, userId);

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Edit(string id)
        {
            var pharmacy = this.pharmaciesService.GetPharmacyById(id);

            var inputModel = new PharmacyInputModel
            {
                Id = id,
                Name = pharmacy.Name,
                Address = pharmacy.Address,
                ContactNumber = pharmacy.ContactNumber,
                ProfileImage = pharmacy.ProfileImage,
                OwnerId = pharmacy.OwnerId,
            };

            ViewBag.Data = inputModel;
            return View();
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(PharmacyInputModel inputModel)
        {
            await this.pharmaciesService.UpdateAsync(inputModel.Name, inputModel.Address, inputModel.ContactNumber, inputModel.ProfileImage, inputModel.Id);

            return this.Redirect("/Pharmacy/List");
        }

        [Authorize]
        public async Task<IActionResult> Delete(string id)
        {
            var meeting = this.pharmaciesService.GetPharmacyById(id);

            await this.pharmaciesService.Delete(id);

            return this.Redirect("/Pharmacy/List");
        }
    }
}

src/Web/DrugTrade.Web/Controllers/ProductController.cs
using DrugTrade.Services.Data;
using DrugTrade.Web.ViewModels.Products;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DrugTrade.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IPharmaciesService pharmaciesService;
        private readonly IProductsService productsService;

        public ProductController(IUsersService usersService, IProductsService productsService, IPharmaciesService pharmaciesService)
        {
            this.usersService = usersService;
            this.productsService = productsService;
            this.pharmaciesService = pharmaciesService;
        }

        public IActionResult Add()
        {
            var userId = this.usersService.GerUserByName(this.User.Identity.Name).Id;
            var pharmacies = this.usersService.GetAllUserPharmacies(userId);


            ViewBag.Pharmacies = pharmacies;
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(ProductInputModel inputModel)
        {
            var pharmacy = inputModel.Pharmacy;

            await this.productsService.AddAsync(inputModel.Name, inputModel.Description, inputModel.Manifacturer, inputModel.Price, inputModel.Quantity, inputModel.Image, pharmacy, this.pharmaciesService.GetPharmacyById(pharmacy));

            return this.Redirect("/");
        }

        [Authorize]
        public async Task<IActionResult> List()
        {
            var products = this.productsService.GetAllProducts();

            var userId = this.usersService.GerUserByName(this.User.Identity.Name).Id;

            foreach (var product in products)
            {
                product.Pharmacy = this.pharmaciesService.GetPharmacyById(product.PharmacyId);
            }

            ProductViewModel viewModel = new ProductViewModel(products, userId, "");

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult Edit(string id)
        {
            var product = this.productsService.GetProductById(id);

            var inputModel = new ProductInputModel
            {
                Id = id,
                Name = product.Name,
                Manifacturer = product.Мanifacturer,
                Description = product.Description,
                Price = product.Price,
                Quantity = product.Quantity,
                Image = product.Image,
            };

            ViewBag.Data = inputModel;
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(ProductInputModel inputModel)
        {
            await this.productsService.UpdateAsync(inputModel.Id, inputModel.Name, inputModel.Description, inputModel.Manifacturer, inputModel.Price, inputModel.Quantity, inputModel.Image);

            return this.Redirect("/Product/List");
        }

        [Authorize]
        public IActionResult Delete(string id)
        {
            var meeting = this.productsService.GetProductById(id);

            this.productsService.Delete(id);

            return this.Redirect("/Product/List");
        }

        [Authorize]
        public async Task<IActionResult> Filter(string pharmacyName)
        {
            var pharmacyId = this.pharmaciesService.GetPharmacyByName(pharmacyName).Id;
            var products = this.productsService.GetProductsByPharmacy(pharmacyId);

            var userId = this.usersService.GerUserByName(this.User.Identity.Name).Id;

            foreach (var product in products)
            {
                product.Pharmacy = this.pharmaciesService.GetPharmacyById(product.PharmacyId);
            }

            ProductViewModel viewModel = new ProductViewModel(products, userId, "");

            return this.View(viewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Filter(ProductInputModel inputModel)
        {
            await this.productsService.UpdateAsync(inputModel.Id, inputModel.Name, inputModel.Description, inputModel.Manifacturer, inputModel.Price, inputModel.Quantity, inputModel.Image);

            return this.Redirect("/Product/List");
        }
    }
}

src/Web/DrugTrade.Web/Views/Shared/_Layout.cshtml
@using DrugTrade.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Аптека
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Pharmacy" asp-action="Add">Добавяне на нова аптека</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Pharmacy" asp-action="List">Всички аптеки</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Продукти
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Product" asp-action="Add">Добави нов продукт</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Product" asp-action="List">Всички продукти</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Поверителност</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Поверителност</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>